name: Run Tests on Push & PR

on:  
  push:
    branches: [main, gamedev] 
  pull_request:
    branches: [main, gamedev]  

jobs:
  test:
    runs-on: ubuntu-latest 

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: run_for_your_life_user
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}  
          POSTGRES_DB: run_for_your_life
        ports:
          - 5432:5432  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  

      - name: Install dependencies
        run: |
          cd gamedev
          npm install  

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL"
          sleep 10
        
      - name: Initialize Database Schema
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  
        run: |
          PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} psql -h dpg-cusf9fl6l47c7386ejjg-a.oregon-postgres.render.com -U run_for_your_life_user -d run_for_your_life -f database/query.sql 

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd gamedev
          npm test  
